top_srcdir   = /data/gitLocalRepo/edu_linux_c/httpd-2.4.41
top_builddir = /data/gitLocalRepo/edu_linux_c/httpd-2.4.41
srcdir       = /data/gitLocalRepo/edu_linux_c/httpd-2.4.41/modules/mappers
builddir     = /data/gitLocalRepo/edu_linux_c/httpd-2.4.41/modules/mappers
VPATH        = /data/gitLocalRepo/edu_linux_c/httpd-2.4.41/modules/mappers

include $(top_srcdir)/build/special.mk

