top_srcdir   = /data/gitLocalRepo/edu_linux_c/httpd-2.4.41
top_builddir = /data/gitLocalRepo/edu_linux_c/httpd-2.4.41
srcdir       = /data/gitLocalRepo/edu_linux_c/httpd-2.4.41/modules/metadata
builddir     = /data/gitLocalRepo/edu_linux_c/httpd-2.4.41/modules/metadata
VPATH        = /data/gitLocalRepo/edu_linux_c/httpd-2.4.41/modules/metadata

include $(top_srcdir)/build/special.mk

