Pre-defined:
	echo "AR       = $(AR)"
	echo "ARFLAGS  = $(ARFLAGS)"
	echo "AS       = $(AS)"
	echo "ASFLAGS  = $(ASFLAGS)"
	echo "CC       = $(CC)"
	echo "CFLAGS   = $(CFLAGS)"
	echo "CXX      = $(CXX)"
	echo "CXXFLAGS = $(CXXFLAGS)"
	echo "LDFLAGS  = $(LDFLAGS)"
	echo ".c.o     = $(.c.o)"

