top_srcdir   = /data/gitLocalRepo/edu_linux_c/httpd-2.4.41
top_builddir = /data/gitLocalRepo/edu_linux_c/httpd-2.4.41
srcdir       = /data/gitLocalRepo/edu_linux_c/httpd-2.4.41/os/unix
builddir     = /data/gitLocalRepo/edu_linux_c/httpd-2.4.41/os/unix
VPATH        = /data/gitLocalRepo/edu_linux_c/httpd-2.4.41/os/unix

LTLIBRARY_NAME    = libos.la
LTLIBRARY_SOURCES = unixd.c

include $(top_srcdir)/build/ltlib.mk
