top_srcdir   = /data/gitLocalRepo/edu_linux_c/httpd-2.4.41
top_builddir = /data/gitLocalRepo/edu_linux_c/httpd-2.4.41
srcdir       = /data/gitLocalRepo/edu_linux_c/httpd-2.4.41/modules/http
builddir     = /data/gitLocalRepo/edu_linux_c/httpd-2.4.41/modules/http
VPATH        = /data/gitLocalRepo/edu_linux_c/httpd-2.4.41/modules/http

include $(top_srcdir)/build/special.mk

