top_srcdir   = /data/gitLocalRepo/edu_linux_c/httpd-2.4.41
top_builddir = /data/gitLocalRepo/edu_linux_c/httpd-2.4.41
srcdir       = /data/gitLocalRepo/edu_linux_c/httpd-2.4.41/srclib
builddir     = /data/gitLocalRepo/edu_linux_c/httpd-2.4.41/srclib
VPATH        = /data/gitLocalRepo/edu_linux_c/httpd-2.4.41/srclib

BUILD_SUBDIRS = $(AP_BUILD_SRCLIB_DIRS)
CLEAN_SUBDIRS = $(AP_CLEAN_SRCLIB_DIRS)

include $(top_builddir)/build/rules.mk
