top_srcdir   = /data/gitLocalRepo/edu_linux_c/httpd-2.4.41
top_builddir = /data/gitLocalRepo/edu_linux_c/httpd-2.4.41
srcdir       = /data/gitLocalRepo/edu_linux_c/httpd-2.4.41/server/mpm
builddir     = /data/gitLocalRepo/edu_linux_c/httpd-2.4.41/server/mpm
VPATH        = /data/gitLocalRepo/edu_linux_c/httpd-2.4.41/server/mpm

SUBDIRS = $(MPM_SUBDIRS)

include $(top_builddir)/build/rules.mk
