top_srcdir   = /data/gitLocalRepo/edu_linux_c/httpd-2.4.41
top_builddir = /data/gitLocalRepo/edu_linux_c/httpd-2.4.41
srcdir       = /data/gitLocalRepo/edu_linux_c/httpd-2.4.41/modules/cache
builddir     = /data/gitLocalRepo/edu_linux_c/httpd-2.4.41/modules/cache
VPATH        = /data/gitLocalRepo/edu_linux_c/httpd-2.4.41/modules/cache

include $(top_srcdir)/build/special.mk

