top_srcdir   = /data/gitLocalRepo/edu_linux_c/httpd-2.4.41
top_builddir = /data/gitLocalRepo/edu_linux_c/httpd-2.4.41
srcdir       = /data/gitLocalRepo/edu_linux_c/httpd-2.4.41/modules/slotmem
builddir     = /data/gitLocalRepo/edu_linux_c/httpd-2.4.41/modules/slotmem
VPATH        = /data/gitLocalRepo/edu_linux_c/httpd-2.4.41/modules/slotmem
# a modules Makefile has no explicit targets -- they will be defined by
# whatever modules are enabled. just grab special.mk to deal with this.
include $(top_srcdir)/build/special.mk
