top_srcdir   = /data/gitLocalRepo/edu_linux_c/httpd-2.4.41
top_builddir = /data/gitLocalRepo/edu_linux_c/httpd-2.4.41
srcdir       = /data/gitLocalRepo/edu_linux_c/httpd-2.4.41/os
builddir     = /data/gitLocalRepo/edu_linux_c/httpd-2.4.41/os
VPATH        = /data/gitLocalRepo/edu_linux_c/httpd-2.4.41/os

SUBDIRS = $(OS_DIR)

include $(top_builddir)/build/rules.mk
