top_srcdir   = /data/gitLocalRepo/edu_linux_c/httpd-2.4.41
top_builddir = /data/gitLocalRepo/edu_linux_c/httpd-2.4.41
srcdir       = /data/gitLocalRepo/edu_linux_c/httpd-2.4.41/server/mpm/event
builddir     = /data/gitLocalRepo/edu_linux_c/httpd-2.4.41/server/mpm/event
VPATH        = /data/gitLocalRepo/edu_linux_c/httpd-2.4.41/server/mpm/event
include $(top_srcdir)/build/special.mk
